[build]
  command = "npm run build"
  publish = "public"

[functions]
  external_node_modules = ["express", "ejs", "cookie-parser", "morgan", "http-errors", "debug"]
  node_bundler = "esbuild"
  included_files = ["views/**/*.ejs", "routes/**/*.js", "public/views/**/*.ejs"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# Redirect all other routes to the Express app for client-side routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200